# Generated by Django 4.1.4 on 2022-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
    ]
