# Generated by Django 4.1.4 on 2022-12-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_isvalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='isValid',
            new_name='is_valid',
        ),
    ]
